#!/bin/bash
#
# updateMailer (gather update information + mail them)
# is a script written by: Bert Deferme <bert@open-future.be>
#
# Description:
# Gather information on updates, and mail them to a specified email address.
#
# Released as GPLv3
#

version="0.1aplha"

#
# Configuration
#

sendTo="updates@open-future.be"

#
# Check for OS and store in $OS / $DIST
#
OS=$(uname -s)
if [ $OS = "SunOS" ];
  then 
  OS=Solaris
elif [ $OS = "Linux" ];
  then
  if [ -f /etc/redhat-release ];
    then
    DIST="Redhat"
    REV=$(cat /etc/redhat-release)
  elif [ -f /etc/debian_version ];
    then
    DIST="Debian"
    REV=$(cat /etc/debian_version)
  fi
fi

echo "updateMailer $version running on $OS $DIST $REV"

#
# Check if tools exist
#

echo ""
echo "... checking for needed tools"

if [[ $DIST == "Redhat" ]];
then
  TOOLS="${TOOLS} yum"
elif [[ $DIST == "Debian" ]];
then
  TOOLS="${TOOLS} apt-get"
fi
NOTOOLS=""
for tool in $TOOLS; do
  TOOLP=$(which $tool 2> /dev/null)
  if [[ x$TOOLP = "x" ]]; then
    NOTOOLS="${NOTOOLS}$tool "
  fi
done

if [[ ! x$NOTOOLS = "x" ]]; then
  echo "ERR: The following needed tools are not installed:"
  echo $NOTOOLS
  echo
  while [[ ! ( $ANSB == "y" || $ANSB == "n" ) ]]; do
  echo
  echo "Continue anyway (y/n)? "
  read -n 1 ANSB
  done
  [[ $ANSB == "n" ]] && echo "Exiting." && exit
fi

#
# Gather system information
#

# hostname
hostname=$(hostname)
